markdown: redcarpet
baseurl: /
name: 'Massachusetts Walks Again'
description: "SCI Awareness Day will be Wednesday, September 13th, 2017
                       Hall of Flags, Noon to 1:00pm
                               (new sound system)"
exclude: ['README.md']
